# Generated by Django 3.1.4 on 2021-02-21 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveJudges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Couple',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(max_length=50)),
                ('surname1', models.CharField(max_length=50)),
                ('name2', models.CharField(max_length=50)),
                ('surname2', models.CharField(max_length=50)),
                ('number', models.IntegerField(default=0)),
                ('fk_session', models.CharField(max_length=150)),
                ('email', models.CharField(default='a@b.it', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Dance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('fk_session', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='DbSession',
            fields=[
                ('id', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Judge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('fk_session', models.CharField(max_length=150)),
                ('id_login', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.CharField(max_length=1600)),
            ],
        ),
        migrations.CreateModel(
            name='Paramether',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('fk_session', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Votation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.FloatField()),
                ('fk_couple', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='couple_v', to='MatchAnalisys.couple')),
                ('fk_dance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dance_v', to='MatchAnalisys.dance')),
                ('fk_judge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judge_v', to='MatchAnalisys.judge')),
                ('fk_parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='param_v', to='MatchAnalisys.paramether')),
                ('fk_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dbsession_v', to='MatchAnalisys.dbsession')),
            ],
        ),
        migrations.CreateModel(
            name='StartSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.IntegerField(default=0)),
                ('fk_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dbsession_ss', to='MatchAnalisys.dbsession')),
            ],
        ),
        migrations.CreateModel(
            name='RandomMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_dance', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='dance_r', to='MatchAnalisys.dance')),
                ('fk_judge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judge_r', to='MatchAnalisys.judge')),
                ('fk_paramether', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='param_r', to='MatchAnalisys.paramether')),
                ('fk_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dbsession_r', to='MatchAnalisys.dbsession')),
            ],
        ),
        migrations.AddConstraint(
            model_name='paramether',
            constraint=models.UniqueConstraint(fields=('name', 'fk_session'), name='Constraint_Paramether'),
        ),
        migrations.AddField(
            model_name='note',
            name='fk_couple',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='couple_n', to='MatchAnalisys.couple'),
        ),
        migrations.AddField(
            model_name='note',
            name='fk_dance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dance_n', to='MatchAnalisys.dance'),
        ),
        migrations.AddField(
            model_name='note',
            name='fk_judge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judge_n', to='MatchAnalisys.judge'),
        ),
        migrations.AddField(
            model_name='note',
            name='fk_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dbsession_n', to='MatchAnalisys.dbsession'),
        ),
        migrations.AddConstraint(
            model_name='judge',
            constraint=models.UniqueConstraint(fields=('name', 'surname', 'fk_session'), name='Constraint_Judge'),
        ),
        migrations.AddConstraint(
            model_name='judge',
            constraint=models.UniqueConstraint(fields=('fk_session', 'id_login'), name='Constraint_Judge2'),
        ),
        migrations.AddConstraint(
            model_name='dance',
            constraint=models.UniqueConstraint(fields=('name', 'fk_session'), name='Constraint_Dance'),
        ),
        migrations.AddConstraint(
            model_name='couple',
            constraint=models.UniqueConstraint(fields=('number', 'fk_session'), name='Constraint_Couple'),
        ),
        migrations.AddConstraint(
            model_name='couple',
            constraint=models.UniqueConstraint(fields=('email', 'fk_session'), name='Constraint_Couple2'),
        ),
        migrations.AddField(
            model_name='activejudges',
            name='fk_judge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judge_aj', to='MatchAnalisys.judge'),
        ),
        migrations.AddField(
            model_name='activejudges',
            name='fk_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dbsession_aj', to='MatchAnalisys.dbsession'),
        ),
    ]
