# Generated by Django 3.1.4 on 2020-12-15 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dance',
            fields=[
                ('id', models.CharField(auto_created=True, max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('fk_session', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='DbSession',
            fields=[
                ('id', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
